### ISSUE TITLE
Sming usage of I2C Port Expander

### ISSUE THREAD

**Issue by hreintke** [jaretburkett/Arduino-I2C-Port-Expander#1]
@jaretburkett : 
Thanks for this library, it was a perfect starting point for my experiments in this.

I plan to use an updated version within the Sming Framework for ESP8266.
The work in progress is in my fork : https://github.com/hreintke/Arduino-I2C-Port-Expander.git
Branch Sming_Updates

Do you want me to PR when finished or keep your version as is.

**Comment by alonewolfx2** [comment]
@hreintke #2 have you any idea?
